### ISSUE TITLE
build and send raw code but not work,Arduino send the same work well....

### ISSUE THREAD

**Issue by IoTServ** [slawekkolodziej/irremote#1]
why,thanks!

**Comment by slawekkolodziej** [comment]
I assume you're sending IR message within a task created by xTaskCreate. It is possible that the task is interrupted by RTOS. Arduino doesn't have "simultaneous" tasks and so, such thing doesn't occur there. To avoid this, set higher priority for IR task, like I did here: https://github.com/slawekkolodziej/ac-remote/blob/master/ac_remote.c#L306

```
xTaskCreate(&wifi_task, "wifi_task", 256, NULL, 2, NULL);
xTaskCreate(&httpd_task, "httpd_task", 128, NULL, 2, NULL);
xTaskCreate(&ir_task, "ir_task", 256, NULL, 3, NULL); // <-- This task has priority set to "3".
xTaskCreate(&mqtt_task, "mqtt_task", 2048, NULL, 2, NULL);
```

Here you can learn more about xTaskCreate: http://www.freertos.org/a00125.html

**Comment by slawekkolodziej** [comment]
Actually, I found a bug and fixed it in https://github.com/slawekkolodziej/irremote/commit/5c1ec504cdd8e4cef5f6905bfea5af9be39815bd
